/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 696b1e10e2c2f12078023213b5c21bf8)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "RESEND_API_KEY">> {}
}
